server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 65a65a
  cloud:
    zookeeper:
      connect-string: 81.68.149.16:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bngel.springcloud.entities
